name = "survey"
version = "1.13.0"
licences = ["Apache-2.0"]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_time = ">= 1.6.0 and < 2.0.0"
filepath = ">= 1.1.0 and < 2.0.0"
mist = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
storail = ">= 3.0.0 and < 4.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
youid = ">= 1.2.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
